from __future__ import annotations

import json
import logging
import shutil
import textwrap
from pathlib import Path
from typing import TYPE_CHECKING

from griptape_nodes.common.project_templates import load_project_template_from_yaml
from griptape_nodes.common.project_templates.directory import DirectoryDefinition
from griptape_nodes.common.project_templates.validation import ProjectValidationInfo, ProjectValidationStatus
from griptape_nodes.node_library.workflow_registry import WorkflowRegistry
from griptape_nodes.retained_mode.events.flow_events import GetTopLevelFlowRequest, GetTopLevelFlowResultSuccess
from griptape_nodes.retained_mode.events.workflow_events import (
    PublishWorkflowResultFailure,
    PublishWorkflowResultSuccess,
    SaveWorkflowRequest,
    SaveWorkflowResultSuccess,
)
from griptape_nodes.retained_mode.griptape_nodes import GriptapeNodes
from griptape_nodes.retained_mode.publishing import WorkflowPackager

from publish_gizmo.nuke_discovery import GIZMO_INSTALL_CUSTOM
from publish_livegroup.nuke_livegroup_builder import NukeLiveGroupBuilder
from publish_livegroup.version_manager import VersionManager

if TYPE_CHECKING:
    from griptape_nodes.retained_mode.events.base_events import ResultPayload

logger = logging.getLogger(__name__)

_LIVEGROUP_SUBDIR = "griptape_livegroups"


def _load_json(path: Path) -> dict:
    """Load JSON from path, returning empty dict if missing or corrupt."""
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _dump_json(data: dict) -> str:
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def _build_livegroups_module(registry_path: Path) -> str:
    """Return the content of griptape_livegroups.py.

    This module is placed in ~/.nuke/ so Nuke's startup Python path picks it up.
    It reads the JSON registry and registers each workflow as a Nodes menu command.
    When a workflow is created, it adds the user knobs to the LiveGroup container
    via the Nuke Python API so run_button.py can access them via nuke.thisNode().
    It also installs a knobChanged callback that prompts the user to reload any
    LiveGroup whose source .nk file has been updated on disk.
    """
    registry_str = str(registry_path).replace("\\", "/")
    return textwrap.dedent(f"""\
        # Auto-generated by Griptape Nodes — do not edit by hand.
        # Re-generated on each LiveGroup publish.
        import json
        import nuke

        _REGISTRY_PATH = {registry_str!r}

        def _load_registry():
            try:
                with open(_REGISTRY_PATH, encoding="utf-8") as _f:
                    return json.load(_f)
            except Exception:
                return {{}}

        def _add_knobs(node, knob_specs):
            for spec in knob_specs:
                knob_type = spec["type"]
                name = spec["name"]
                label = spec.get("label", name)
                if knob_type == "tab":
                    node.addKnob(nuke.Tab_Knob(name, label))
                elif knob_type == "divider":
                    node.addKnob(nuke.Text_Knob(name, label))
                elif knob_type == "string":
                    k = nuke.String_Knob(name, label)
                    if spec.get("default"):
                        k.setValue(spec["default"])
                    if spec.get("disabled"):
                        k.setFlag(nuke.READ_ONLY)
                    node.addKnob(k)
                elif knob_type == "multiline_string":
                    k = nuke.Multiline_Eval_String_Knob(name, label)
                    if spec.get("default"):
                        k.setValue(spec["default"])
                    if spec.get("disabled"):
                        k.setFlag(nuke.READ_ONLY)
                    node.addKnob(k)
                elif knob_type == "file":
                    k = nuke.File_Knob(name, label)
                    if spec.get("default"):
                        k.setValue(spec["default"])
                    if spec.get("disabled"):
                        k.setFlag(nuke.READ_ONLY)
                    node.addKnob(k)
                elif knob_type == "bool":
                    k = nuke.Boolean_Knob(name, label)
                    if spec.get("default") is not None:
                        k.setValue(bool(spec["default"]))
                    node.addKnob(k)
                elif knob_type == "int":
                    k = nuke.Int_Knob(name, label)
                    if spec.get("default") is not None:
                        k.setValue(int(spec["default"]))
                    node.addKnob(k)
                elif knob_type == "double":
                    k = nuke.Double_Knob(name, label)
                    if spec.get("default") is not None:
                        k.setValue(float(spec["default"]))
                    node.addKnob(k)
                elif knob_type == "enumeration":
                    k = nuke.Enumeration_Knob(name, label, spec.get("choices", []))
                    if spec.get("default_index") is not None:
                        k.setValue(spec["default_index"])
                    node.addKnob(k)
                elif knob_type == "pyscript":
                    node.addKnob(nuke.PyScript_Knob(name, label, spec.get("code", "")))
                elif knob_type == "invisible_string":
                    k = nuke.String_Knob(name, "")
                    k.setFlag(nuke.INVISIBLE)
                    k.setValue(spec.get("value", ""))
                    node.addKnob(k)

        def _make_create_livegroup(nk_path, knob_specs):
            def _create():
                lg = nuke.createNode("LiveGroup", inpanel=False)
                lg["file"].setValue(nk_path)
                _add_knobs(lg, knob_specs)
            return _create

        _registry = _load_registry()
        _menu = nuke.menu("Nodes")
        for _name, _entry in _registry.items():
            _nk_path = _entry["nk_path"]
            _knob_specs = _entry.get("knobs", [])
            _display = _name.replace("_", " ").title()
            _menu.addCommand(f"Griptape/{{_display}}", _make_create_livegroup(_nk_path, _knob_specs))

        def _griptape_livegroup_check_updates():
            try:
                node = nuke.thisNode()
                if nuke.thisKnob().name() == "showPanel":
                    if hasattr(node, "isLocalizationOutdated") and node.isLocalizationOutdated():
                        if nuke.ask("A newer version of this workflow is available. Reload?"):
                            node.reload()
            except Exception:
                pass

        nuke.addKnobChanged(_griptape_livegroup_check_updates, nodeClass="LiveGroup")
    """)


class NukeLiveGroupPublisher:
    """Publishes a Griptape workflow as a Nuke LiveGroup.

    On first publish: packages the full workflow bundle (via WorkflowPackager),
    generates a .nk LiveGroup source file, and registers it in ~/.nuke/menu.py.

    On republish: if only the workflow file changed (libraries unchanged), skips
    the full packaging step and only copies the updated workflow file before
    regenerating the .nk file. This makes incremental republishes fast.

    The .nk file is overwritten in place on each publish. Any open LiveGroup
    instances in Nuke will detect the change via isLocalizationOutdated() and
    can reload via reload().
    """

    def __init__(self, workflow_name: str, metadata: dict | None = None) -> None:
        self._workflow_name = workflow_name
        self._metadata: dict = metadata or {}
        self._packager = WorkflowPackager(workflow_name)

    def publish_workflow(self) -> ResultPayload:
        try:
            self._packager.emit_progress(5.0, "Validating workflow...")
            errors = self._validate()
            if errors:
                return PublishWorkflowResultFailure(result_details="\n".join(str(e) for e in errors))

            self._packager.emit_progress(5.0, "Extracting workflow shape...")
            workflow_shape = GriptapeNodes.WorkflowManager().extract_workflow_shape(self._workflow_name)
            logger.info("Workflow shape: %s", workflow_shape)

            self._packager.emit_progress(5.0, "Saving workflow...")
            workflow = WorkflowRegistry.get_workflow_by_name(self._workflow_name)
            save_result = GriptapeNodes.handle_request(SaveWorkflowRequest(file_name=Path(workflow.file_path).stem))
            if not isinstance(save_result, SaveWorkflowResultSuccess):
                return PublishWorkflowResultFailure(result_details="Failed to save workflow before packaging.")

            install_dir = self._resolve_install_path()
            if install_dir is None:
                msg = "Install path is not set."
                raise ValueError(msg)

            workflow_file_path = Path(WorkflowRegistry.get_complete_file_path(workflow.file_path))
            workflow_stem = workflow_file_path.stem
            companion_dir = install_dir / _LIVEGROUP_SUBDIR / workflow_stem
            version_manager = VersionManager(companion_dir)

            library_refs = getattr(workflow.metadata, "node_libraries_referenced", [])

            if version_manager.needs_full_repackage(library_refs):
                self._packager.emit_progress(5.0, "Packaging workflow bundle...")
                self._packager.package_to_folder(companion_dir, workflow)
                self._write_nuke_project_template(companion_dir)
                self._packager.emit_progress(5.0, "Writing runner scripts...")
                runner_src = Path(__file__).parent.parent / "publish_gizmo" / "nuke_workflow_runner.py"
                shutil.copy2(runner_src, companion_dir / "run_workflow.py")
                run_button_src = Path(__file__).parent.parent / "publish_gizmo" / "run_button.py"
                shutil.copy2(run_button_src, companion_dir / "run_button.py")
            else:
                self._packager.emit_progress(5.0, "Lightweight republish — updating workflow file only...")
                companion_dir.mkdir(parents=True, exist_ok=True)
                dest_workflow = companion_dir / workflow_file_path.name
                shutil.copy2(workflow_file_path, dest_workflow)

            # Generate the .nk file
            self._packager.emit_progress(10.0, "Generating LiveGroup .nk file...")
            dest_workflow = companion_dir / workflow_file_path.name
            new_version = (version_manager.current_version() or 0) + 1
            nk_path = companion_dir / f"{workflow_stem}.nk"

            # Archive the existing .nk before overwriting
            version_manager.archive_current_nk(nk_path)

            builder = NukeLiveGroupBuilder(
                workflow_name=workflow_stem,
                workflow_shape=workflow_shape,
                companion_dir=str(companion_dir),
                workflow_file=str(dest_workflow),
                version=new_version,
            )
            nk_text = builder.generate()
            nk_path.write_text(nk_text, encoding="utf-8")
            logger.info("LiveGroup .nk written to: %s", nk_path)

            # Record the version
            version_manager.record_version(dest_workflow, library_refs)

            # Register the LiveGroup in ~/.nuke/menu.py
            self._packager.emit_progress(5.0, "Registering in ~/.nuke/menu.py...")
            menu_py_path = self._register_in_nuke_menu(nk_path, workflow_stem, builder.get_knob_spec())

            self._save_publish_config()

            self._packager.emit_progress(10.0, "LiveGroup installed successfully!")

            current_version = version_manager.current_version()
            result_details = (
                f"LiveGroup v{current_version} installed to: {nk_path}\n\n"
                f"Registered in: {menu_py_path}\n"
                f"Restart Nuke to see '{workflow_stem.replace('_', ' ').title()}' in the Griptape menu.\n\n"
                f"To update an existing LiveGroup after republishing:\n"
                f"  Right-click the node \u2192 'Reload' (or call node.reload() in Script Editor)."
            )

            return PublishWorkflowResultSuccess(
                published_workflow_file_path=str(nk_path),
                skip_published_workflow_registration=True,
                result_details=result_details,
            )
        except Exception as e:
            logger.exception("Failed to publish workflow '%s' as LiveGroup", self._workflow_name)
            return PublishWorkflowResultFailure(result_details=f"Failed to publish workflow: {e}")

    def _write_nuke_project_template(self, companion_dir: Path) -> None:
        """Overwrite project.yml with absolute paths so outputs save in the LiveGroup folder."""
        project_yml = companion_dir / "project.yml"
        if not project_yml.exists():
            return

        validation_info = ProjectValidationInfo(status=ProjectValidationStatus.GOOD)
        template = load_project_template_from_yaml(project_yml.read_text(encoding="utf-8"), validation_info)
        if template is None:
            logger.warning("Could not parse project.yml for Nuke path rewrite. Skipping.")
            return

        absolute_path_overrides = {
            "outputs": str(companion_dir / "outputs"),
            "inputs": str(companion_dir / "inputs"),
            "temp": str(companion_dir / "temp"),
        }
        for dir_name, override_path in absolute_path_overrides.items():
            if dir_name in template.directories:
                template.directories[dir_name] = DirectoryDefinition(
                    name=dir_name,
                    path_macro=override_path,
                )

        project_yml.write_text(template.to_yaml(include_comments=False), encoding="utf-8")

    def _validate(self) -> list[Exception]:
        errors: list[Exception] = []
        start_flow = self._get_nuke_start_flow_node()
        if start_flow is None:
            errors.append(ValueError("No NukeStartFlow node found in the workflow."))
            return errors
        install_dir = self._resolve_install_path()
        if install_dir is None:
            errors.append(ValueError("Install path is not configured. Please set it in the publish dialog."))
        return errors

    def _register_in_nuke_menu(self, nk_path: Path, workflow_name: str, knob_specs: list[dict]) -> Path:
        """Register this LiveGroup in Nuke's startup menu.

        Maintains a structured JSON registry at ~/.nuke/griptape_livegroups.json and
        writes a static Python module at ~/.nuke/griptape_livegroups.py that reads it.
        Then ensures `import griptape_livegroups` appears in ~/.nuke/menu.py (added once).

        Returns the path to ~/.nuke/menu.py.
        """
        dot_nuke = Path.home() / ".nuke"
        dot_nuke.mkdir(parents=True, exist_ok=True)

        # 1. Update the JSON registry — store nk_path + knob specs per workflow
        registry_path = dot_nuke / "griptape_livegroups.json"
        registry = _load_json(registry_path)
        registry[workflow_name] = {"nk_path": str(nk_path), "knobs": knob_specs}
        registry_path.write_text(_dump_json(registry), encoding="utf-8")

        # 2. Overwrite the Python module with the current registry baked in
        module_path = dot_nuke / "griptape_livegroups.py"
        module_path.write_text(_build_livegroups_module(registry_path), encoding="utf-8")

        # 3. Ensure menu.py imports the module (added at most once)
        menu_py = dot_nuke / "menu.py"
        existing = menu_py.read_text(encoding="utf-8") if menu_py.exists() else ""
        import_line = "import griptape_livegroups"
        if import_line not in existing:
            separator = "\n" if existing and not existing.endswith("\n") else ""
            menu_py.write_text(existing + separator + import_line + "\n", encoding="utf-8")

        logger.info("Registered LiveGroup '%s' in %s", workflow_name, menu_py)
        return menu_py

    def _resolve_install_path(self) -> Path | None:
        choice = self._metadata.get("gizmo_install_path")
        if choice == GIZMO_INSTALL_CUSTOM:
            choice = self._metadata.get("custom_gizmo_path")
        if not choice:
            return None
        return Path(choice)

    def _save_publish_config(self) -> None:
        start_flow = self._get_nuke_start_flow_node()
        if start_flow is None:
            return
        start_flow.metadata["publish_config"] = {
            "nuke": self._metadata.get("nuke"),
            "gizmo_install_path": self._metadata.get("gizmo_install_path"),
            "custom_gizmo_path": self._metadata.get("custom_gizmo_path"),
            "publish_format": "livegroup",
        }

    def _get_nuke_start_flow_node(self):  # noqa: ANN202
        result = GriptapeNodes.handle_request(GetTopLevelFlowRequest())
        if not isinstance(result, GetTopLevelFlowResultSuccess) or result.flow_name is None:
            return None
        control_flow = GriptapeNodes.FlowManager().get_flow_by_name(result.flow_name)
        for node in control_flow.nodes.values():
            if node.__class__.__name__ == "NukeStartFlow":
                return node
        return None
